name: Test VAPOR Python API

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-vapor:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Set up conda-forge channel and create a conda environment
      - name: Configure Conda
        run: |
          conda config --add channels conda-forge
          conda create -n vapor-env python=3.9 conda-build -y
          conda activate vapor-env

      # Build VAPOR from source
      - name: Build VAPOR
        working-directory: conda
        run: |
          DEBUG_BUILD=false MAP_IMAGES_PATH="tests/images" conda build .

      # Extract the package location
      - name: Extract tar file
        id: package-path
        run: |
          echo "package_path=$(conda build . --output)" >> $GITHUB_ENV
          mkdir -p ~/channel/linux-64
          mv ${{ env.package_path }} ~/channel/linux-64/
        working-directory: conda

      # Create a local channel and install the package
      - name: Create Local Channel and Install Package
        run: |
          conda index ~/channel
          conda install -c file://$HOME/channel vapor -y
        shell: bash

      # Test the installation
      - name: Test VAPOR Installation
        run: |
          conda activate vapor-env
          python -c "import vapor"
